# Generated by Django 4.1.5 on 2023-01-16 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.CharField(blank=True, max_length=255)),
                ('teamnumber', models.CharField(blank=True, max_length=255, unique=True)),
                ('teamname', models.CharField(blank=True, max_length=255)),
                ('shortname', models.CharField(blank=True, max_length=255)),
                ('tla', models.CharField(blank=True, max_length=255)),
                ('crest', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('clubColors', models.CharField(blank=True, max_length=255)),
                ('coach', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('playedgames', models.IntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=255)),
                ('won', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('lost', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('goalsfor', models.IntegerField(blank=True, null=True)),
                ('goalsagainst', models.IntegerField(blank=True, null=True)),
                ('goalsdifference', models.IntegerField(blank=True, null=True)),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
