# Generated by Django 4.1.5 on 2023-01-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_areacode_alter_team_clubcolors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
