# Generated by Django 4.1.5 on 2023-01-30 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltime_home', models.IntegerField(blank=True, null=True)),
                ('fulltime_away', models.IntegerField(blank=True, null=True)),
                ('halftime_home', models.IntegerField(blank=True, null=True)),
                ('halftime_away', models.IntegerField(blank=True, null=True)),
                ('matchid', models.CharField(blank=True, max_length=255, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winTeam', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('utcDate', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('awayTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='teams.team')),
                ('final_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.score')),
                ('homeTeam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='teams.team')),
            ],
        ),
    ]
