# Generated by Django 4.1.5 on 2023-01-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
