# Generated by Django 4.1.5 on 2023-01-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='penalties',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='top_scorer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
