# Generated by Django 4.1.5 on 2023-01-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['goals']},
        ),
    ]
