# Generated by Django 4.1.5 on 2023-01-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_assists_player_goals_player_penalties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='penalties',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
